services:
  
  db:
    image: mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    
    environment:
      - MYSQL_DATABASE=clinica
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=
    expose:
      - 3306
  app:
    depends_on:
      - db
    image: app-cli_app
    restart: always
   
    expose:
      - 3000

volumes:
  db_data:

  